DEV_AWS_BUCKET : 'otoyabi.dev' #ENV['AWS_BUCKET'],
DEV_AWS_ACCESS_KEY_ID: 'AKIAIRZQKABYBWRUTCDQ' #ENV['AWS_ACCESS_KEY_ID']
DEV_AWS_SECRET_ACCESS_KEY: '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' # ENV['AWS_SECRET_ACCESS_KEY']

PRO_AWS_BUCKET : 'otoyabi' #ENV['AWS_BUCKET'],
PRO_AWS_ACCESS_KEY_ID: 'AKIAJJYF3VETKWDDFGBA' #ENV['AWS_ACCESS_KEY_ID']
PRO_AWS_SECRET_ACCESS_KEY: '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' # ENV['AWS_SECRET_ACCESS_KEY']

GMAIL_USER_NAME: 
GMAIL_PASSWORD: 

SECRET_TOKEN: '444fbbcc34ac3c6ee0941c17da29a4386f0ef3f5eee3257ffa1cb1f2431e7db9dc9b418b2affc7dd2931ebee01d07ac3e3113445ab49dc1742a5d457e46e662e'
