development:
  adapter: postgresql
  encoding: unicode
  database: mashin_development
  pool: 5
  username: deploye
  password: hamid
  host: localhost

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: mashin_test
#   pool: 5
#   username: mashin
#   password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: mashin_production
#   pool: 5
#   username: mashin
#   password:
